POST http://127.0.0.1:8000/api/job/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxNTc4NDc2LCJpYXQiOjE3NzE1NzgxNzYsImp0aSI6ImUxNmJlMzRlMjJjODRhOGZhYTM4MDYxOTExYTdkYjQ3IiwidXNlcl9pZCI6IjIifQ.lyzRVPjr8OukBPgHK4bAv1Y0HtyBamc4Jqh2Mtd_9ZA

{
  "customer_name": "patu5",
  "customer_phone": "145446524",
  "address": "Ramnagar",
  "device_type": "laptop",
  "customer_email": "pratiksha12@gmail.com",
  "device_brand": "msi",
  "device_model": "model15",
  "serial_number": "12121114",
  "problem_description": "GPU"
}

###

POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "patu",
    "password": "patu@123"
}