# Generated by Django 6.0.1 on 2026-02-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_otp_locked_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='expries_at',
            new_name='expires_at',
        ),
    ]
