# Generated by Django 6.0.1 on 2026-01-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_customuser_phone_customuser_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineerprofile',
            old_name='employer',
            new_name='employer_id',
        ),
    ]
