# Generated by Django 6.0.1 on 2026-02-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_employer_engineerprofile_employer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('owner', 'owner'), ('engineer', 'engineer')], default='engineer', max_length=150),
        ),
    ]
